### ISSUE TITLE
No such command "js" in OS X 10.6

### ISSUE THREAD

**Issue by tricon** [hallettj/jslint.vim#10]
I don't think OS X includes the "js" command anymore. Regardless, running: "sudo port install spidermonkey" resolves this issue.

**Comment by mat813** [comment]
Well, my snow leopard has it, only, it's not called js, and it's not in the PATH, I run jslint manually with :

```
JS_CMD=/System/Library/Frameworks/JavaScriptCore.framework/Resources/jsc ~/bin/jslint whatever.js
```

**Comment by hallettj** [comment]
Recent versions of the plugin check for the executable that @mat813 mentions.  That executable seems to be present on pretty much every OS X installation.

Thanks for the bug report!
