### ISSUE TITLE
es5 compat

### ISSUE THREAD

**Issue by wavded** [hallettj/jslint.vim#17]
How in sync is this with the jslint repo, I'm getting errors for "reserved words" on property types, is there a way to enable "es5 mode?"

http://tech.groups.yahoo.com/group/jslint_com/message/1260

**Comment by hallettj** [comment]
The latest version of jslint.vim includes jslint 2012-02-23.  From now on the jslint version can be upgraded by replacing the ftplugin/javascript/jslint/jslint-core.js file with the latest version of jslint.

**Comment by ghost** [comment]
Maybe this could be documented in the README?
