### ISSUE TITLE
spidermonkey-bin not availble in Ubuntu Lucid

### ISSUE THREAD

**Issue by ghost** [hallettj/jslint.vim#2]
Alternative js interpreter rhino does not support readline().

**Comment by ghost** [comment]
The spidermonkey-bin package is available from this ppa:

https://edge.launchpad.net/~launchpad/+archive/ppa

And appears to work fine.  Not really a fix but a decent workaround.

**Comment by smith** [comment]
I was getting around to make a version that uses narwhal or node, since nowadays I'm more likely to have one of those around than spidermonkey. Let me know if anybody's interested and I can find some time.

**Comment by wizonesolutions** [comment]
I had no trouble getting spidermonkey-bin. It's in lucid-universe.

**Comment by hallettj** [comment]
The latest development version of jslint.vim supports rhino and node.js in addition to spidermonkey.  I do not recommend using rhino though: it has to start up a JVM instance every time jslint runs which creates a lengthy delay, and the latest version of jslint.vim checks for errors in near real time so jslint gets run frequently.
