### ISSUE TITLE
when copying pasting comments get messed up

### ISSUE THREAD

**Issue by bartvde** [hallettj/jslint.vim#25]
When I copy and paste something like:

```
        /** api: event[beforelayerselectionchange]
         *  Fired before the selected set of layers changes.  Listeners 
         *  can return ``false`` to stop the selected layers from being 
         *  changed.
         *
         *  Listeners arguments:
         *
         *  * layerRecord - ``GeoExt.data.LayerRecord`` the record of the
         *    selected layer, or null if no layer is selected.
         */
```

I end up with instead:

```
        /** api: event[beforelayerselectionchange]
```
-              \*  Fired before the selected set of layers changes.  Listeners 
-                           \*  can return `false` to stop the selected layers from being 
-                                        \*  changed.
-                                                     *
-                                                                  \*  Listeners arguments:
-                                                                               *
-                                                                                            \*  \* layerRecord - `GeoExt.data.LayerRecord` the record of the
-                                                                                                         \*    selected layer, or null if no layer is selected.
-                                                                                                                      */

**Comment by hallettj** [comment]
Are you pasting by pressing <kbd>Ctrl</kbd>+<kbd>v</kbd>, or something like that, while in insert mode?  That method of pasting tends to produce problems in vim.  I believe that you will get better results using vim's native paste commands.

For example, the system clipboard usually maps to a register called `+`.  So to paste from the clipboard you can go into command mode and use the command, `"+p`.

If you want to access the oldschool Unix clipboard, that maps to a register called `*`.  The oldschool clipboard in Linux, `*`, is the one that contains the last piece of text that you selected.  The other clipboard, `+`, is the one that contains text that you copied with <kbd>Ctrl</kbd>+<kbd>c</kbd> or <kbd>Ctrl</kbd>+<kbd>x</kbd>, etc.

There is more information here: http://vim.wikia.com/wiki/Accessing_the_system_clipboard
