### ISSUE TITLE
jshint.vim plugin hangs macvim on osx lion

### ISSUE THREAD

**Issue by Gozala** [hallettj/jslint.vim#26]
Have no idea what happens, but it looks like macvim works just fine on lion without jshint plugin enabled and completely freezes app if jshint is enabled. It hangs macvim when switching from input mode to normal mode.

**Comment by csexton** [comment]
I was able to resolve this by updating the latest jslint.js from Douglas Crockford's repo

A quick work around would be to update the file: 

```
curl https://raw.github.com/douglascrockford/JSLint/master/jslint.js > .vim/ftplugin/javascript/jslint/jslint-core.js
```

(your path to jslint-core may differ if you use pathogen or vundle)

This is included in https://github.com/hallettj/jslint.vim/pull/27

**Comment by csexton** [comment]
Turns out that updating jslint.js doesn't fix the hang. It gets vim past some load errors, but MacVim on Lion still hangs when leaving insert mode.

**Comment by csexton** [comment]
More digging into this issue, I have found that there are some problems with the require when using node (v0.4.10) -- to work around this for now I simply cat'd jslint-core.js to the top of runjslint.js. Perhaps someone with better node-fu would have some insight. The includes work fine with squirrelfish.

The other interesting thing is it only seems to hang in the GUI MacVim, when using MacVim in the terminal (I aliased vim to `/Applications/MacVim.app/Contents/MacOS/Vim`) everything seems to work.

In the gui it will process the file once, but when the autocommand for entering normal mode is run it hangs. It will also hang if you run `:JSLintUpdate`.

No clue why it runs the first time, but freezes on the second. It will freeze running with node or jsc (squirrelfish).

**Comment by csexton** [comment]
This is a MacVim issue. It is being tracked in their issue tracker [here](http://code.google.com/p/macvim/issues/detail?id=346).

This appears when using zsh and MacVim. Possible work-arounds: 
- pass "-f" into mvim when launching
- use bash

for now, I put this in my .zshrc:

```
mvim() { /Applications/MacVim.app/Contents/MacOS/Vim -g -f $* & }
```

**Comment by b4winckler** [comment]
This issue has been fixed in [snapshot 60](https://github.com/b4winckler/macvim/downloads).

(I would close the issue but I don't have permission to.)

**Comment by hallettj** [comment]
I'm guessing that the change in pull request #14 would also work around this issue, if you don't have a sufficiently recent version of MacVim.
