### ISSUE TITLE
jslint-core.js crashes with spidermonkey 1.8.5

### ISSUE THREAD

**Issue by Olivia5k** [hallettj/jslint.vim#29]
jslint-core.js:5655: ReferenceError: assignment to undeclared variable exports
using spidermonkey 1.8.5 2011-03-31

The fix is easy; just add a var statement to the declaration on that very row. I'm not sure how kosher that is, but it makes it work.

**Comment by feroda** [comment]
This happens also to me using nodejs 0.6.6-3

Thanks for the quickfix. It seems to work.

**Comment by hallettj** [comment]
Fixed in the latest version of the plugin.  Thanks for the report!
