### ISSUE TITLE
jslint.vim:154 crashes with JavaScriptCore on OSX 10.7 Lion

### ISSUE THREAD

**Issue by phuesler** [hallettj/jslint.vim#31]
As a workaround, use node.js: 

export JS_CMD=`which node`

**Comment by respectTheCode** [comment]
Thanks that fixed it for me.

**Comment by hallettj** [comment]
Thanks for suggesting this workaround!  I think that this issue is fixed in the latest version of the plugin.  There is more info in issue #13.
