### ISSUE TITLE
can't install on; error message enclosed

### ISSUE THREAD

**Issue by mfeif** [hallettj/jslint.vim#35]
I have tried various ways of installing. I use pathogen, would appreciate instructions on how to do that right...

But I also tried just putting the ftplugin in .vim/... the best I ever got was a message upon vim startup:

Error detected while processing function <SNR>14_JSLint:
line    40:
could not invoke JSLint!

I tried grep'ing around in the plugin, but couldn't find any of those symbols.

Thanks.

**Comment by Tigraine** [comment]
Same here .. doesn't work

**Comment by hallettj** [comment]
There is some discussion of similar problems in issue #13.  I have made some changes in the latest version that might fix your problems.  If not, the latest version at least gives more descriptive error output.

If you are still having problems with the latest version, please leave a comment on issue #13.
