### ISSUE TITLE
Change Highlight Color

### ISSUE THREAD

**Issue by vjsingh** [hallettj/jslint.vim#38]
Is there any way to change the color used for highlighting errors? I have a black background in my terminal, and with the red highlighting characters of certain syntax colors disappear

Thanks, tried looking around but couldn't find where its specified.

**Comment by vjsingh** [comment]
Figured it out. Put this after loading a colorscheme in your ~/.vimrc

hi clear SpellBad
hi SpellBad cterm=underline,bold ctermfg=magenta

Obviously, change the second line to configure how you want (ctermbg is highlighting)

**Comment by nathanmacinnes** [comment]
My preferred setting for this is:

```
hi clear SpellBad
hi SpellBad cterm=underline,bold ctermfg=white ctermbg=red
```

This still makes it stand out as red, but makes sure the text is white so you can see it clearly. (You don't need syntax highlighting in your lint-errored text, do you?)

**Comment by eedeep** [comment]
nice @nathanmacinnes works well for me thanks

**Comment by micrub** [comment]
@nathanmacinnes Super! Thanks!
