### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [hallettj/jslint.vim#41]
I can't tell if anyone is going to maintain this project or not.  The last commit was over a year ago.  There are pending pull requests that I'd like to see merged into the project.  Does anyone know if this project is going to be updated?

Thanks,

TR

**Comment by hallettj** [comment]
You are right, I have been neglecting this project.  I finally went and merged a bunch of pull requests and fixed some bugs.  I plan to try to be more responsive.

If you want to try out other plugins that may be more actively developed, I have a list of candidates in the "Alternative Plugins" section of the [README](https://github.com/hallettj/jslint.vim#readme) for this project.  Another plugin that looks promising is [Syntastic](https://github.com/scrooloose/syntastic).

**Comment by ghost** [comment]
@hallettj Thanks for responding and for giving some attention to the plugin.  I noticed the plugin is still at version 0.7 2010-09-26 at vim.org.  Might be nice if you could update that when you get a chance.
