### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by cizmazia** [hallettj/jslint.vim#6]
How can I install the plugin correctly for GVim on Windows XP? I copied the plugin into ftplugin. After :JSLintUpdate, the following errors are displayed:

Error detected while processing function <SNR>33_JSLintUpdate..<SNR>33_JSLInt:
line 23:
E484: Can't open file C:\DOCUME~1\MICHAL~1\LOCALS~1\Temp\TIoAC.tmp
line 25:
could not invoke JSLint!

Thank you,
Michal

**Comment by mattn** [comment]
This will be fix with my small changes. :)
http://github.com/hallettj/jslint.vim/pull/5

**Comment by ethervoid** [comment]
I'm having the same issue :(

Error detected while processing function <SNR>51_JSLint
line 23:
E484: Can't open file C:\DOCUME~1\MARIO~1_DEF\CONFIG~1\Temp\VioB21A.tmp
line 25:
could not invoke JSLint!

My enviroment is: 
- Windows XP
- GVIM: 7.3.46
- JSLing: Last version from Git

Thank you,
Mario

**Comment by foxbunny** [comment]
Having the same issues on Windows 7 and version of the plugin from Git (as of 2012-04-15).

**Comment by ghost** [comment]
Same issue :(

**Comment by mattn** [comment]
I just sent pull-request.
